//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RollPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation
    {
        public int OperationID { get; set; }
        public Nullable<int> ParentOperationID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Channel { get; set; }
        public Nullable<int> Quantity { get; set; }
    }
}
